trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      sudo apt update
      sudo apt install make
      cd $(Build.SourcesDirectory)
      make build
    displayName: 'Run make build'